apiVersion: v1
kind: Namespace
metadata:
  name: storagedemo

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storagedemo-claim
  namespace: storagedemo
  labels:
    app: storagedemo-claim
spec:
  storageClassName: azurefile-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: Pod
metadata:
  name: "storagedemo-pod"
  namespace: storagedemo
  labels:
    app: "storagedemo-pod"
spec:
  containers:
  - name: storagedemo-pod
    image: "mcr.microsoft.com/cbl-mariner/base/core:2.0"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
    - name: storage
      mountPath: /mnt/externalstorage
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: storagedemo-claim

---

