apiVersion: v1
kind: ConfigMap
metadata:
  name: application-settings
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  settings.ini: | 
    stage = {{ .Values.stage }}

    [backend]
    url = {{ .Values.backendUrl }}
---

